### PR TITLE
master -> indigo-devel

### PR DESCRIPTION
**Pull request by chapulina**
See discussion on this PR:

https://github.com/ros-visualization/rqt_rviz/pull/8

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Changing the branch name to make releases from looks good. But the last release shouldn't be changed - you will need to run `bloom-release` for that since it needs to generate the necessary Debian control files etc.

**Comment by chapulina** [comment]
Ha, I think that's what I was missing, thanks. Reverted the version. The changelog and tags are ready, I guess I can run `bloom-release` once this PR is merged, right?

**Review by dirk-thomas — APPROVED** [review]

**Comment by dirk-thomas** [comment]
The branches will also need to be changed in the distribution files (for each distro, `doc` as well as `source` entry), e.g. https://github.com/ros/rosdistro/blob/c23128afc41fb978419d563a5f0bfd8c1e8f2ceb/kinetic/distribution.yaml#L10619

**Comment by dirk-thomas** [comment]
> I guess I can run bloom-release once this PR is merged, right?

Yes. When bloom creates the PRs for you it is easy to edit the branch names (I mentioned) in these PRs through the GitHub interface.

**Comment by chapulina** [comment]
Here it is: https://github.com/ros/rosdistro/pull/18293, I guess it's safer to do it in parts? Bump the version after the branches have been fixed?

**Pull request merged**
